version: '3.8'
services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_DB=strategy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/bitnami/postgresql
